spring.application.name=ecommerce-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm
spring.datasource.username=postgres
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
